### ISSUE TITLE
What can I do for you?

### ISSUE THREAD

**Issue by dannyvankooten** [Rarst/AMA#1]
It feels only right to ask you this after asking us for so many times. So here it goes. What can I do for you?

**Comment by Rarst** [comment]
This is a tough one.

I suck at asking for things. Likely because I suck at wanting things. Likely because at times I feel like wanting things is life’s way of being a fucking disappointment.

Last couple years were a shit show for me. I lost a lot of things and I failed at many things.

What I want now is to have a direction again. That’s not something one can ask for, is it? At least not a person like me.

Maybe once I have a direction again... I will ask for help to get there.

(No, I absolutely won’t, not going to happen)
