### ISSUE TITLE
What are some of your experiences building non-WordPress sites?

### ISSUE THREAD

**Issue by daggerhart** [Rarst/AMA#3]
Have you used many frameworks or other CMSes? If so, what did you like or dislike most about these other solutions, and did these experiences change the way you develop?

**Comment by Rarst** [comment]
Let me get my timeline straight... I started using WordPress in 2008, 23 years old.

My first job had been maintaining a web site, I've been 16 I think, so around 2001. That one taught me that websites _are_ just HTML plus CSS. And that inappropriate use of tools (be it FrontPage or Dreamweaver) is a good way to mess those up.

After that I went away from webdev for a while, so my second non–WP phase had started around 2013, 28 years old and 4+ years into primarily building with WordPress.

I had went with Silex for my needs at the time and it had been my primary non–WP framework since. It solves enough of menial details, without bogging me down in involved opinionated conventions.

That period allowed me catch up on areas that WP lacks in, such as: dependency management, templating, routing, and most importantly HTTP protocol.

I explore other frameworks sporadically, the recent ones I tried were Bolt, October, and Grav. I was most impressed with Grav out of those. But I hadn't built any sites with any of them yet.

So overall I had been at this for many years and through many things, though primarily in PHP realm, which is my language of choice.

If I try to summarize my experiences into key points:

1. HTML, CSS, and HTTP are foundational to web development. I am not especially _great_ with them, but I had long learned that these are the ones that matter.
2. The rest of the shebang are essentially tools to produce and manipulate the trio above.
3. Anything can be done in a wonderful way and a horrible way.
4. One person’s wonderful is another person’s horrible.
5. Frameworks are primarily compilations of opinions, code is just an implementation detail.
6. People and projects are much less objective than they think they are.
7. There is significant component of fashion to [web] development.

Overall I wouldn't say that my non–WP experiences drastically _changed_ how I do web dev.

But they had most certainly allowed me to progress in a much more well–rounded way. To have better selection of tools & techniques at my disposal and perspective on using them appropriately.
