### ISSUE TITLE
Who are your favorite writers?

### ISSUE THREAD

**Issue by pollyplummer** [Rarst/AMA#4]
I am a regular reader of your blog and I think you communicate very well in English. You have an interesting turn of phrase that is enjoyable to read. When did you first learn English? Who are your favorite writers (in any language) that you grew up reading?

**Comment by Rarst** [comment]
## English

I went to school with extended English program, which forced me to have a little more solid foundation than is typical around here.

In university the level of English course was below what I already attained, so I went on to read in English and later download TV shows in it as Internet got faster.

I tend to say that my English is a peculiar mix of American pronunciation, British spelling, and Russian language structure. These days any less casual writing I do goes through Hemingway and Grammarly. Helps me have that pileup of complicated sentences and missing articles under control.

As I got heavier into online and tech eventually I started _thinking_ about it in English. It is actually hard for me to talk about my work in Russian.

## Writers

Curiously I think about writers in terms of... _affinity_ rather than likability. It is somewhat hard to explain.

One of my favorites series is The Land of Elves by **Denis Chekalov**. They are not _great_ books. Heck, some of them are probably not even _good_ books. But they are books that work like my mind does, in both good and not so much ways.

On the other side of the spectrum there are Strugatksy brothers and Pratchett. I can’t read them. I can’t,

As a kid I remember reading adventure books, such as White Jaguar by **Arkady Fiedler** and Le Capitaine Casse–Cou by **Louis Henri Boussenard**. Though I probably completely skirted over social and racial aspects of them at the time.

The Chronicles of Amber by **Roger Zelazny** is my all–time most read. I have read the series something over thirty times I think. Though I first read it in early age, his other works took me much longer to grew into. I suspect the Russian translation had somewhat polished off his typical mystic edge off it.

I’ve enjoyed books by **Sergei Lukyanenko** in my early teens, but later I completely grew out of them.

Anita Blake: Vampire Hunter series by **Laurell K. Hamilton** was the first series I’ve read in English, if I remember right. I enjoyed early books a lot for their take on urban fantasy and was sad when it later pivoted into basically porn.

That about covers growing up, I think. :)
