### ISSUE TITLE
What does your ideal 'job' look like

### ISSUE THREAD

**Issue by jonathanbossenger** [Rarst/AMA#7]
In a perfect world, what are you doing every day to earn a living?

**Comment by Rarst** [comment]
This is an uncomfortable one since I effectively don’t have a job at the moment. And if I knew what ideal one would be — I’d be looking for it.

The thing is I barely care about having a job. I come from post–Soviet environment, where you are railroaded into going to school, going to university, getting a job. Some job. Whatever job. Just have it. And if it makes you miserable — that’s what vodka is for.

So I don’t deeply care for having a job. And I also don’t drink.

Out of things I’ve read and watched over years on the topic the closest that resonated with me was “autonomy, mastery, purpose” framework.

**Autonomy** — I don’t like to be _managed_, though I like to be _cooperated_ with. Just put something complex, interesting, and messy in front of me and let me go at it. Make occasional encouraging noises. Tell me when I start to screw up. Ask me to explain. Have my back.

**Mastery** — I don’t like to do things half way. I’d rather not start at all on something that I don’t believe I have interest and resources in doing well (this is why I don’t play chess for example). I’d be unbearable perfectionists, but this is smoothly balanced out by my laziness.

**Purpose** — I don’t like busy work. Though I am sure some things I do look like that to people, but that’s usually when I am _learning_ the heck out of tackling something menial and looking for way to get better at it or get rid of it. One of my main purposes is automation. I think no person deserves to be stuck doing work that computer can do. Humans are too wonderful and valuable for that. So I aspire to free them where I can.

This kind of adds up to not being able to imagine a _for life_ kind of a job for myself. My ideal outcome at a job is automating myself out of it and moving on to other things that need me. I can’t be stuck in something that I feel I could do forever and not be done.

What does this adds up to as a “job” really? Hell if I know.
